### ISSUE TITLE
Тест

### ISSUE THREAD

**Issue by Fodense** [Kenor007/Clevertec-GradleTask#1]
Тест должен отвечать за одно действие, а не за всё что только можно)

Лучшим решение в данном случае было бы разделить этот тест на два: положительные кейсы и отрицательные при этом используя @ParameterizedTest

https://github.com/Kenor007/Clevertec-GradleTask/blob/75c2b71fdadd1d9e345eb24a7f52c51f950a01c3/src/test/java/ru/clevertec/StringUtilsTest.java#L11

**Comment by Kenor007** [comment]
Исправил тесты, разделил на разные кейсы, используя  @ParameterizedTest
